import { Building } from '@/lib/types';

export const DEMO_BUILDINGS: Building[] = [
  {
    id: '1',
    city_registry_id: 'ASH-2024-001',
    name: 'בניין החזית לים',
    address: 'רחוב הרצל 45, אשדוד',
    neighborhood: 'מרכז העיר',
    lat: 31.8039,
    lng: 34.7522,
    year_built: 1965,
    year_built_verified: true,
    year_built_source: 'רישום עיריה',
    architect: 'אדריכל דוד בן גוריון',
    architect_verified: true,
    protection_level: 'א',
    current_use: 'דירות עיר',
    total_built_area: 2500,
    floors: 5,
    construction_type: 'בטון ואבן ירושלמית',
    status: 'בתהליך',
    is_complex: false,
    documentation_reason: 'הערך האדריכלי של הבניין',
    initiator: 'יחידת השימור העירונית',
    created_at: new Date('2024-01-15').toISOString(),
    updated_at: new Date('2024-05-20').toISOString(),
  },
  {
    id: '2',
    city_registry_id: 'ASH-2024-002',
    name: 'מצפה הפחם',
    address: 'שדרות ישראל 123, אשדוד',
    neighborhood: 'עזמר',
    lat: 31.8150,
    lng: 34.7650,
    year_built: 1956,
    year_built_verified: true,
    year_built_source: 'תיעוד ממשלתי',
    architect: 'אדריכל יעקב ניסן',
    architect_verified: true,
    protection_level: 'ב',
    current_use: 'מוזיאון',
    total_built_area: 1800,
    floors: 3,
    construction_type: 'אבן כורכר',
    status: 'הוגש',
    is_complex: false,
    documentation_reason: 'חשיבות היסטורית',
    initiator: 'משרד התרבות',
    created_at: new Date('2024-02-10').toISOString(),
    updated_at: new Date('2024-05-15').toISOString(),
  },
  {
    id: '3',
    city_registry_id: 'ASH-2024-003',
    name: 'קומפלקס ספורט לשעבר',
    address: 'רחוב הקיבוץ 78, אשדוד',
    neighborhood: 'מרכז ספורט',
    lat: 31.7950,
    lng: 34.7400,
    year_built: 1972,
    year_built_verified: true,
    year_built_source: 'תיעוד עיריה',
    architect: 'חברת אדריכלים בארץ',
    architect_verified: true,
    protection_level: 'ג',
    current_use: 'מתחם מגורים חדש',
    total_built_area: 8500,
    floors: 7,
    construction_type: 'בטון ברזל',
    status: 'לא_התחיל',
    is_complex: true,
    documentation_reason: 'מורשת תרבותית קהילתית',
    initiator: 'משפחות התושבים',
    created_at: new Date('2024-03-05').toISOString(),
    updated_at: new Date('2024-05-10').toISOString(),
  },
  {
    id: '4',
    city_registry_id: 'ASH-2024-004',
    name: 'בנק המזרחי המשכנתא',
    address: 'שדרות הנשיא 56, אשדוד',
    neighborhood: 'מרכז העיר',
    lat: 31.8070,
    lng: 34.7580,
    year_built: 1968,
    year_built_verified: true,
    year_built_source: 'רישום בנק',
    architect: 'אדריכל שלמה ביסקי',
    architect_verified: true,
    protection_level: 'ב',
    current_use: 'משרדים',
    total_built_area: 3200,
    floors: 6,
    construction_type: 'טיח גיר ואבן',
    status: 'אושר',
    is_complex: false,
    documentation_reason: 'ערך אדריכלי חשוב',
    initiator: 'יחידת השימור העירונית',
    created_at: new Date('2024-01-25').toISOString(),
    updated_at: new Date('2024-05-22').toISOString(),
  },
  {
    id: '5',
    city_registry_id: 'ASH-2024-005',
    name: 'מבנה התאטרון הישן',
    address: 'רחוב אבא אבן 12, אשדוד',
    neighborhood: 'מרכז העיר',
    lat: 31.8020,
    lng: 34.7550,
    year_built: 1962,
    year_built_verified: true,
    year_built_source: 'ארכיון עיריה',
    architect: 'אדריכל יוסף זרטל',
    architect_verified: true,
    protection_level: 'מונומנט',
    current_use: 'חוזרת לתאטרון',
    total_built_area: 4100,
    floors: 2,
    construction_type: 'אבן ירושלמית מרובה',
    status: 'הוחזר',
    is_complex: false,
    documentation_reason: 'משמעות תרבותית',
    initiator: 'חברת התאטרון הקומוני',
    created_at: new Date('2024-04-01').toISOString(),
    updated_at: new Date('2024-05-18').toISOString(),
  },
];