import { Building } from '@/lib/types';

export const DEMO_BUILDINGS: Building[] = [
  {
    id: '1',
    city_registry_id: 'ASH-001',
    name: 'המגדלור בגבעת יונה',
    address: 'כביש 4 אדר׳ חיה',
    neighborhood: 'רובע א׳',
    lat: 31.8243, lng: 34.6578,
    parcel: '2077/2',
    style: 'מגדל ניווט',
    historical_periods: ['תקופה ישראלית'],
    owner: 'ממ"י / עיריית אשדוד',
    documentation_reason: 'היסטורית, אדריכלית',
    current_use: 'קיים - סגור לציבור',
    protection_level: 'א',
    status: 'לא_התחיל',
    is_complex: false, year_built_verified: false, architect_verified: false,
    building_type: 'מגדל ניווט',
    preservation_reasons: ['היסטורית', 'אדריכלית'],
    priority_level: 'גבוהה',
    full_description: 'בנוי בראשית תקופת הנמל. גובה 138 מטר. זכוכית מן המגדלור בתל אביב. סגור לציבור משנת 2009.',
    created_at: new Date('2024-01-01').toISOString(),
    updated_at: new Date('2024-01-01').toISOString(),
  },
  {
    id: '2',
    city_registry_id: 'ASH-002',
    name: 'גשר עד הלום / הפילבוקס / עמדת ויקרס',
    address: 'פארק עד הלום',
    neighborhood: 'נחל לכיש',
    lat: 31.7976, lng: 34.6254,
    parcel: '182/33, 182/49-51',
    style: 'גשר היסטורי',
    historical_periods: ['תקופה ישראלית'],
    owner: 'ממ"י / עיריית אשדוד',
    documentation_reason: 'לאומית, היסטורית',
    current_use: 'קיים',
    protection_level: 'א',
    status: 'לא_התחיל',
    is_complex: false, year_built_verified: false, architect_verified: false,
    building_type: 'גשר היסטורי',
    preservation_reasons: ['לאומית', 'היסטורית'],
    priority_level: 'גבוהה',
    full_description: 'בנוי בסוף המאה 19 על יסודות רומיים. פוצץ 15/5/48. הפילבוקס - מצדית בטון (1936). עמדת ויקרס - עמדת צה"ל.',
    created_at: new Date('2024-01-01').toISOString(),
    updated_at: new Date('2024-01-01').toISOString(),
  },
  {
    id: '3',
    city_registry_id: 'ASH-003',
    name: 'אובליסק מיצרי',
    address: 'פארק עד הלום',
    neighborhood: 'נחל לכיש',
    lat: 31.7976, lng: 34.6254,
    parcel: '182/33',
    style: 'אנדרטה',
    historical_periods: ['תקופה ישראלית'],
    owner: 'עיריית אשדוד',
    documentation_reason: 'לאומית, היסטורית',
    current_use: 'קיים',
    protection_level: 'ב',
    status: 'לא_התחיל',
    is_complex: false, year_built_verified: true, year_built: 1990, architect_verified: false,
    building_type: 'אנדרטה',
    preservation_reasons: ['לאומית', 'היסטורית'],
    priority_level: 'בינונית',
    full_description: 'הוקם בשנת 1990 לזכר חללי מצרים. כתובות בערבית, אנגלית, עברית והירוגליפים.',
    created_at: new Date('2024-01-01').toISOString(),
    updated_at: new Date('2024-01-01').toISOString(),
  },
  {
    id: '4',
    city_registry_id: 'ASH-004',
    name: 'הקליפורניות (בנק הפועלים + בנק לאומי)',
    address: 'רח׳ הורדים 7 ו-3',
    neighborhood: 'רובע א׳',
    lat: 31.8219, lng: 34.6512,
    parcel: '2061/161',
    style: 'בנק / מסחר',
    historical_periods: ['תקופה ישראלית'],
    owner: 'ממ"י',
    documentation_reason: 'היסטורית',
    current_use: 'קיים',
    protection_level: 'ב',
    status: 'לא_התחיל',
    is_complex: false, year_built_verified: false, architect_verified: false,
    building_type: 'בנק / מסחר',
    preservation_reasons: ['היסטורית'],
    priority_level: 'בינונית',
    full_description: 'בנק הפועלים הראשון והבנק הלאומי הראשון באשדוד. בנויות בראשית שנות 60. מבנים חד-קומתיים ראשונים בעיר.',
    created_at: new Date('2024-01-01').toISOString(),
    updated_at: new Date('2024-01-01').toISOString(),
  },
  {
    id: '5',
    city_registry_id: 'ASH-005',
    name: 'בית קנדה - מרכז קליטה',
    address: 'רח׳ רוגוזין / שבי ציון',
    neighborhood: 'רובע א׳',
    lat: 31.8228, lng: 34.6467,
    parcel: '2061/111',
    style: 'מרכז קליטה',
    historical_periods: ['תקופה ישראלית'],
    owner: 'הסוכנות היהודית',
    documentation_reason: 'אדריכלית, היסטורית',
    current_use: 'פעיל - שופץ',
    protection_level: 'א',
    status: 'לא_התחיל',
    is_complex: false, year_built_verified: false, architect_verified: true, architect: 'משה לופנפלד',
    building_type: 'מרכז קליטה',
    preservation_reasons: ['אדריכלית', 'היסטורית'],
    priority_level: 'גבוהה',
    full_description: 'תוכנן על ידי משה לופנפלד. בטון חשוף. 2 חצרות פנימיות גדולות. דירות זעירות (15 מ"ר). שופץ בשנים אחרונות.',
    created_at: new Date('2024-01-01').toISOString(),
    updated_at: new Date('2024-01-01').toISOString(),
  },
  {
    id: '6',
    city_registry_id: 'ASH-006',
    name: 'בית הכנסת הקראי — ענן הנשיא',
    address: 'רח׳ האצל 7',
    neighborhood: 'רובע א׳',
    lat: 31.8205, lng: 34.6498,
    parcel: '2061/64',
    style: 'בית כנסת',
    historical_periods: ['תקופה ישראלית'],
    owner: 'עיריית אשדוד',
    documentation_reason: 'היסטורית, תרבותית',
    current_use: 'קיים - פעיל',
    protection_level: 'א',
    status: 'לא_התחיל',
    is_complex: false, year_built_verified: false, architect_verified: false,
    building_type: 'בית כנסת',
    preservation_reasons: ['היסטורית', 'תרבותית'],
    priority_level: 'גבוהה',
    full_description: 'אשדוד - הריכוז הגדול של קראים בישראל (3000+ משפחות). מקום מרכזי בתרבות קראית. תפילה פעמיים ביום.',
    created_at: new Date('2024-01-01').toISOString(),
    updated_at: new Date('2024-01-01').toISOString(),
  },
  {
    id: '7',
    city_registry_id: 'ASH-007',
    name: 'מרכז רובעי א׳',
    address: 'רח׳ רוגוזין / שבי ציון',
    neighborhood: 'רובע א׳',
    lat: 31.8235, lng: 34.6485,
    parcel: '2077/129-157',
    style: 'מרכז מסחרי',
    historical_periods: ['תקופה ישראלית'],
    owner: 'פרטיים',
    documentation_reason: 'אדריכלית, היסטורית',
    current_use: 'קיים',
    protection_level: 'א',
    status: 'לא_התחיל',
    is_complex: false, year_built_verified: false, architect_verified: false,
    building_type: 'מרכז מסחרי',
    preservation_reasons: ['אדריכלית', 'היסטורית'],
    priority_level: 'גבוהה',
    full_description: 'הלב של רובע א׳. משמר תכנון עיר ראשוני. קומת קרקע מסחרית, קולונדה, משרדים בשתי קומות על עמודים, בריכת מים.',
    created_at: new Date('2024-01-01').toISOString(),
    updated_at: new Date('2024-01-01').toISOString(),
  },
  {
    id: '8',
    city_registry_id: 'ASH-008',
    name: 'הגן האדום',
    address: 'רח׳ חיבת ציון 8',
    neighborhood: 'רובע א׳',
    lat: 31.8222, lng: 34.6481,
    parcel: '2077/161',
    style: 'גן ילדים',
    historical_periods: ['תקופה ישראלית'],
    owner: 'עיריית אשדוד',
    documentation_reason: 'היסטורית',
    current_use: 'קיים',
    protection_level: 'ב',
    status: 'לא_התחיל',
    is_complex: false, year_built_verified: false, architect_verified: false,
    building_type: 'גן ילדים',
    preservation_reasons: ['היסטורית'],
    priority_level: 'בינונית',
    full_description: 'בנוי בראשית שנות 60, צבוע אדום. הגננת הראשונה - רחל לנגסנר.',
    created_at: new Date('2024-01-01').toISOString(),
    updated_at: new Date('2024-01-01').toISOString(),
  },
  {
    id: '9',
    city_registry_id: 'ASH-009',
    name: 'לשכת עבודה',
    address: 'רח׳ הראשונים 7',
    neighborhood: 'רובע א׳',
    lat: 31.8198, lng: 34.6523,
    parcel: '2086/78',
    style: 'משרד ציבורי',
    historical_periods: ['תקופה ישראלית'],
    owner: 'ר"מי / פרטיים',
    documentation_reason: 'היסטורית',
    current_use: 'קיים',
    protection_level: 'ב',
    status: 'לא_התחיל',
    is_complex: false, year_built_verified: false, architect_verified: false,
    building_type: 'משרד ציבורי',
    preservation_reasons: ['היסטורית'],
    priority_level: 'בינונית',
    full_description: 'בנוי בראשית שנות 60. שימש כלשכת עבודה לבוגרים ולנוער. כיום - חכירה משרד פרטי.',
    created_at: new Date('2024-01-01').toISOString(),
    updated_at: new Date('2024-01-01').toISOString(),
  },
  {
    id: '10',
    city_registry_id: 'ASH-010',
    name: 'בית מלון ראשון',
    address: 'רח׳ הראשונים 43',
    neighborhood: 'רובע א׳',
    lat: 31.8198, lng: 34.6523,
    parcel: '2085/22',
    style: 'בית מלון',
    historical_periods: ['תקופה ישראלית'],
    owner: 'פרטיים',
    documentation_reason: 'היסטורית',
    current_use: 'קיים',
    protection_level: 'ב',
    status: 'לא_התחיל',
    is_complex: false, year_built_verified: false, architect_verified: false,
    building_type: 'בית מלון',
    preservation_reasons: ['היסטורית'],
    priority_level: 'בינונית',
    full_description: 'בנוי בראשית שנות 60. מבנה "שכון" בן 3 קומות. שימש מאוחר יותר כמשרד קצין העיר.',
    created_at: new Date('2024-01-01').toISOString(),
    updated_at: new Date('2024-01-01').toISOString(),
  },
  {
    id: '11',
    city_registry_id: 'ASH-011',
    name: 'פארק נחל לכיש',
    address: 'נחל לכיש',
    neighborhood: 'נחל לכיש',
    lat: 31.805, lng: 34.635,
    style: 'פארק',
    historical_periods: ['תקופה ישראלית'],
    owner: 'ממ"י / חנ"י',
    documentation_reason: 'נופית, אקולוגית',
    current_use: 'קיים',
    protection_level: 'א',
    status: 'לא_התחיל',
    is_complex: false, year_built_verified: false, architect_verified: false,
    building_type: 'פארק',
    preservation_reasons: ['נופית', 'אקולוגית'],
    priority_level: 'גבוהה',
    full_description: 'מסדרון אקולוגי. שמירה על פרוזדור חי וביולוגי. אזור רגישות נופית וסביבתית גבוהה.',
    created_at: new Date('2024-01-01').toISOString(),
    updated_at: new Date('2024-01-01').toISOString(),
  },
  {
    id: '12',
    city_registry_id: 'ASH-012',
    name: 'שדרת השקמים',
    address: 'דרום (שד׳ השקמים)',
    neighborhood: 'דרום',
    lat: 31.785, lng: 34.64,
    style: 'גנון / שדרה',
    historical_periods: ['תקופה ישראלית', 'תקופות קדומות'],
    owner: 'ממ"י / עיריית אשדוד',
    documentation_reason: 'אקולוגית, נופית',
    current_use: 'קיים',
    protection_level: 'ב',
    status: 'לא_התחיל',
    is_complex: false, year_built_verified: false, architect_verified: false,
    building_type: 'גנון / שדרה',
    preservation_reasons: ['אקולוגית', 'נופית'],
    priority_level: 'בינונית',
    full_description: 'שדרה היסטורית. שמירה על מערכת אקולוגית.',
    created_at: new Date('2024-01-01').toISOString(),
    updated_at: new Date('2024-01-01').toISOString(),
  },
  {
    id: '13',
    city_registry_id: 'ASH-013',
    name: 'תל מור',
    address: 'דרום אשדוד',
    neighborhood: 'דרום',
    lat: 31.7654, lng: 34.6412,
    style: 'תל ארכאולוגי',
    historical_periods: ['תקופות קדומות'],
    owner: 'קרקע ציבורית',
    documentation_reason: 'ארכאולוגית',
    current_use: 'קיים',
    protection_level: 'א',
    status: 'לא_התחיל',
    is_complex: false, year_built_verified: false, architect_verified: false,
    building_type: 'תל ארכאולוגי',
    preservation_reasons: ['ארכאולוגית'],
    priority_level: 'גבוהה',
    full_description: 'תקופה פלשתית-רומית-פרסית. שרידי יישוב מהסוללה האשורית.',
    created_at: new Date('2024-01-01').toISOString(),
    updated_at: new Date('2024-01-01').toISOString(),
  },
  {
    id: '14',
    city_registry_id: 'ASH-014',
    name: 'מצודת אשדוד ים',
    address: 'חוף הים',
    neighborhood: 'חוף',
    lat: 31.8076, lng: 34.6089,
    style: 'מצודה ארכאולוגית',
    historical_periods: ['תקופות קדומות'],
    owner: 'ממ"י',
    documentation_reason: 'ארכאולוגית, נופית',
    current_use: 'קיים',
    protection_level: 'א',
    status: 'לא_התחיל',
    is_complex: false, year_built_verified: false, architect_verified: false,
    building_type: 'מצודה ארכאולוגית',
    preservation_reasons: ['ארכאולוגית', 'נופית'],
    priority_level: 'גבוהה',
    full_description: 'טיילת חוף. מצודה מימית. משמרת בתב"ע 122/101/02/3.',
    created_at: new Date('2024-01-01').toISOString(),
    updated_at: new Date('2024-01-01').toISOString(),
  },
];
