import { Building } from '@/lib/types';

export const DEMO_BUILDINGS: Building[] = [
  {
    id: '1',
    city_registry_id: 'ASH-001',
    name: 'המגדלור בגבעת יונה',
    address: 'כביש 4 אדר׳ חיה',
    neighborhood: 'רובע א׳',
    lat: 31.8243, lng: 34.6578,
    parcel: '2077/2',
    style: 'מגדל ניווט',
    historical_periods: ['תקופה ישראלית'],
    owner: 'ממ"י / עיריית אשדוד',
    documentation_reason: 'היסטורית, אדריכלית',
    current_use: 'קיים - סגור לציבור',
    protection_level: 'א',
    status: 'לא_התחיל',
    is_complex: false, year_built_verified: false, architect_verified: false,
    building_type: 'מגדל ניווט',
    preservation_reasons: ['היסטורית', 'אדריכלית'],
    priority_level: 'גבוהה',
    full_description: 'בנוי בראשית תקופת הנמל. גובה 138 מטר, מגדל הניווט הגבוה בישראל. ניווט ספינות בדפוס שלושה הבזקים כל 20 שניות. סגור לציבור משנת 2009, משמש כיום כמאגר מים.',
    additional_info: 'נמצא בגבעת יונה — הגבעה הגבוהה ביותר באשדוד (53 מ׳ מעל פני הים). תוכנן לשרת את נמל אשדוד בראשית שנות ה-60. הזכוכית הדיאופטרית הגיעה מהמגדלור הישן בתל אביב.',
    created_at: new Date('2024-01-01').toISOString(),
    updated_at: new Date('2024-01-01').toISOString(),
  },
  {
    id: '2',
    city_registry_id: 'ASH-002',
    name: 'גשר עד הלום / הפילבוקס / עמדת ויקרס',
    address: 'פארק עד הלום',
    neighborhood: 'נחל לכיש',
    lat: 31.7976, lng: 34.6254,
    parcel: '182/33, 182/49-51',
    style: 'גשר היסטורי',
    historical_periods: ['תקופה ישראלית', 'תקופה מנדטורית'],
    owner: 'ממ"י / עיריית אשדוד',
    documentation_reason: 'לאומית, היסטורית',
    current_use: 'קיים - פארק לאומי',
    protection_level: 'א',
    status: 'לא_התחיל',
    is_complex: false, year_built_verified: false, architect_verified: false,
    building_type: 'גשר היסטורי',
    preservation_reasons: ['לאומית', 'היסטורית'],
    priority_level: 'גבוהה',
    full_description: 'גשר אבן ממאה ה-13 (תקופה ממלוכית) על יסודות רומיים, חוצה את נחל לכיש. פוצץ ב-12.5.1948 על ידי גדוד גבעתי לעצור את ההתקדמות המצרית — "עד הלום ולא תוסיף". הפילבוקס — מצדית בטון בריטית (1936). עמדת ויקרס — עמדת צה"ל משנות ה-50.',
    additional_info: 'אתר הנצחה לאומי. כאן נעצרה ההתקדמות המצרית במלחמת העצמאות. הגשר הוכרז כאתר מורשת. הפארק מנוהל על ידי עיריית אשדוד.',
    gov_sources: ['https://en.wikipedia.org/wiki/Ad_Halom'],
    created_at: new Date('2024-01-01').toISOString(),
    updated_at: new Date('2024-01-01').toISOString(),
  },
  {
    id: '3',
    city_registry_id: 'ASH-003',
    name: 'אובליסק מיצרי',
    address: 'פארק עד הלום',
    neighborhood: 'נחל לכיש',
    lat: 31.7980, lng: 34.6260,
    parcel: '182/33',
    style: 'אנדרטה',
    historical_periods: ['תקופה ישראלית'],
    owner: 'עיריית אשדוד',
    documentation_reason: 'לאומית, היסטורית',
    current_use: 'קיים',
    protection_level: 'ב',
    status: 'לא_התחיל',
    is_complex: false, year_built_verified: true, year_built: 1990, architect_verified: false,
    building_type: 'אנדרטה',
    preservation_reasons: ['לאומית', 'היסטורית'],
    priority_level: 'בינונית',
    full_description: 'אנדרטה הוקמה בשנת 1990 לאחר הסכם השלום ישראל-מצרים (1979), לזכר חיילים מצרים שנפלו בקרב עד הלום. כתובות בערבית, אנגלית, עברית והירוגליפים. אחד מסמלי הפיוס ישראלי-מצרי.',
    additional_info: 'הוקם ביוזמת שני הצדדים לאחר הסכם השלום. מהווה ביטוי חריג לפיוס ישראלי-ערבי. הכתובת ההירוגליפית מוסיפה ממד היסטורי עתיק.',
    created_at: new Date('2024-01-01').toISOString(),
    updated_at: new Date('2024-01-01').toISOString(),
  },
  {
    id: '4',
    city_registry_id: 'ASH-004',
    name: 'הקליפורניות (בנק הפועלים + בנק לאומי)',
    address: 'רח׳ הורדים 7 ו-3',
    neighborhood: 'רובע א׳',
    lat: 31.8219, lng: 34.6512,
    parcel: '2061/161',
    style: 'בנק / מסחר',
    historical_periods: ['תקופה ישראלית'],
    owner: 'ממ"י',
    documentation_reason: 'היסטורית',
    current_use: 'קיים',
    protection_level: 'ב',
    status: 'לא_התחיל',
    is_complex: false, year_built_verified: false, architect_verified: false,
    building_type: 'בנק / מסחר',
    preservation_reasons: ['היסטורית'],
    priority_level: 'בינונית',
    full_description: 'בנק הפועלים הראשון ובנק לאומי הראשון באשדוד. בנויות בראשית שנות ה-60 כמבנים חד-קומתיים ראשונים בעיר. כינויין "הקליפורניות" בשל חיפוי הלוחות המיוחד. מייצגות את ראשית הפעילות הכלכלית בעיר הצעירה.',
    additional_info: 'מהמבנים הציבוריים הראשונים שנבנו באשדוד. עדות לפעילות הבנקאית שהחלה בד בבד עם הקמת הנמל. הסגנון מהווה דוגמה לאדריכלות תנועה מודרנית ישראלית של שנות ה-60.',
    created_at: new Date('2024-01-01').toISOString(),
    updated_at: new Date('2024-01-01').toISOString(),
  },
  {
    id: '5',
    city_registry_id: 'ASH-005',
    name: 'בית קנדה — מרכז קליטה',
    address: 'רח׳ רוגוזין / שבי ציון',
    neighborhood: 'רובע א׳',
    lat: 31.8228, lng: 34.6467,
    parcel: '2061/111',
    style: 'מרכז קליטה',
    historical_periods: ['תקופה ישראלית'],
    owner: 'הסוכנות היהודית',
    documentation_reason: 'אדריכלית, היסטורית',
    current_use: 'פעיל - שופץ',
    protection_level: 'א',
    status: 'לא_התחיל',
    is_complex: false, year_built_verified: false, architect_verified: true, architect: 'משה לופנפלד',
    building_type: 'מרכז קליטה',
    preservation_reasons: ['אדריכלית', 'היסטורית'],
    priority_level: 'גבוהה',
    full_description: 'מרכז קליטה תוכנן על ידי האדריכל משה לופנפלד. בטון חשוף בסגנון ברוטליסטי. 2 חצרות פנימיות גדולות לאוורור. דירות זעירות (15 מ"ר) לקליטת עולים חדשים. ממן על ידי הממשלה הקנדית. שופץ בשנים אחרונות ועדיין פעיל.',
    additional_info: 'ממן על ידי הממשלה הקנדית כסיוע לישראל בקליטת עלייה. אחד ממרכזי הקליטה הראשונים שהוקמו באשדוד. מהווה עדות לגל העלייה הגדול של שנות ה-50-60.',
    created_at: new Date('2024-01-01').toISOString(),
    updated_at: new Date('2024-01-01').toISOString(),
  },
  {
    id: '6',
    city_registry_id: 'ASH-006',
    name: 'בית הכנסת הקראי — ענן הנשיא',
    address: 'רח׳ האצל 7',
    neighborhood: 'רובע א׳',
    lat: 31.8091, lng: 34.6443,
    parcel: '2061/64',
    style: 'בית כנסת',
    historical_periods: ['תקופה ישראלית'],
    owner: 'עיריית אשדוד',
    documentation_reason: 'היסטורית, תרבותית',
    current_use: 'קיים - פעיל',
    protection_level: 'א',
    status: 'לא_התחיל',
    is_complex: false, year_built_verified: false, architect_verified: false,
    building_type: 'בית כנסת',
    preservation_reasons: ['היסטורית', 'תרבותית'],
    priority_level: 'גבוהה',
    full_description: 'בית הכנסת הקראי הגדול בישראל, ממוקם באשדוד — הריכוז הגדול ביותר של קהילה קראית בישראל (מעל 3,000 משפחות). נקרא על שם ענן בן דוד (700-800 לסה"נ), מייסד הכת הקראית. תפילה פעמיים ביום, שמירה על מסורת נפרדת מהרבנות.',
    additional_info: 'הקראים הם עדה יהודית שאינה מקבלת את סמכות התלמוד. רוב הקראים בישראל עלו ממצרים בשנות ה-50. אשדוד היא מרכז הפעילות הקראית הגדול בישראל. בית הכנסת מהווה ציר תרבותי-דתי מרכזי.',
    gov_sources: ['https://www.heritage-center.org.il/'],
    created_at: new Date('2024-01-01').toISOString(),
    updated_at: new Date('2024-01-01').toISOString(),
  },
  {
    id: '7',
    city_registry_id: 'ASH-007',
    name: 'מרכז רובעי א׳',
    address: 'רח׳ רוגוזין / שבי ציון',
    neighborhood: 'רובע א׳',
    lat: 31.8235, lng: 34.6485,
    parcel: '2077/129-157',
    style: 'מרכז מסחרי',
    historical_periods: ['תקופה ישראלית'],
    owner: 'פרטיים',
    documentation_reason: 'אדריכלית, היסטורית',
    current_use: 'קיים',
    protection_level: 'א',
    status: 'לא_התחיל',
    is_complex: false, year_built_verified: false, architect_verified: false,
    building_type: 'מרכז מסחרי',
    preservation_reasons: ['אדריכלית', 'היסטורית'],
    priority_level: 'גבוהה',
    full_description: 'הלב הפועם של רובע א׳ — שכונת האם של אשדוד. משמר את עיקרון התכנון המקורי של העיר: קומת קרקע מסחרית עם קולונדה (עמודים), משרדים בשתי קומות על עמודים, בריכת מים ציבורית. תכנן על פי עקרונות CIAM של האדריכל שרון בתקופת הקמת העיר.',
    additional_info: 'רובע א׳ נוסד בשנות ה-50 כשכונת אם של אשדוד. המרכז הרובעי תוכנן לשמש קהילה שלמה. הקולונדה והעמודים מאפיינים את האדריכלות הציבורית הישראלית של אותה תקופה.',
    created_at: new Date('2024-01-01').toISOString(),
    updated_at: new Date('2024-01-01').toISOString(),
  },
  {
    id: '8',
    city_registry_id: 'ASH-008',
    name: 'הגן האדום',
    address: 'רח׳ חיבת ציון 8',
    neighborhood: 'רובע א׳',
    lat: 31.8222, lng: 34.6481,
    parcel: '2077/161',
    style: 'גן ילדים',
    historical_periods: ['תקופה ישראלית'],
    owner: 'עיריית אשדוד',
    documentation_reason: 'היסטורית',
    current_use: 'קיים',
    protection_level: 'ב',
    status: 'לא_התחיל',
    is_complex: false, year_built_verified: false, architect_verified: false,
    building_type: 'גן ילדים',
    preservation_reasons: ['היסטורית'],
    priority_level: 'בינונית',
    full_description: 'גן הילדים הראשון של אשדוד, בנוי בראשית שנות ה-60 וצבוע אדום — הצבע שהקנה לו את שמו. הגננת הראשונה: רחל לנגסנר. עוזרות: ז׳וליאט אניג׳ר ואסתר ג׳נח. מסמל את ראשית חיי הקהילה בעיר הצעירה.',
    additional_info: 'מהמוסדות הציבוריים הראשונים שנפתחו ברובע א׳. צבעו האדום הבולט הפך לסמל עבור הדור הראשון של ילדי אשדוד. שימש גן ילדים פעיל עד לשנים האחרונות.',
    created_at: new Date('2024-01-01').toISOString(),
    updated_at: new Date('2024-01-01').toISOString(),
  },
  {
    id: '9',
    city_registry_id: 'ASH-009',
    name: 'לשכת עבודה',
    address: 'רח׳ הראשונים 7',
    neighborhood: 'רובע א׳',
    lat: 31.8115, lng: 34.6475,
    parcel: '2086/78',
    style: 'משרד ציבורי',
    historical_periods: ['תקופה ישראלית'],
    owner: 'ר"מי / פרטיים',
    documentation_reason: 'היסטורית',
    current_use: 'קיים',
    protection_level: 'ב',
    status: 'לא_התחיל',
    is_complex: false, year_built_verified: false, architect_verified: false,
    building_type: 'משרד ציבורי',
    preservation_reasons: ['היסטורית'],
    priority_level: 'בינונית',
    full_description: 'בנוי בראשית שנות ה-60 ושימש כלשכת עבודה לבוגרים ולנוער. עדות לפעילות ההסתדרות ומשרד העבודה בעיר הצעירה. בשנת 1966 טיפל במשבר תעסוקה חמור (1,700 פועלים). כיום: חכירה כמשרד פרטי.',
    additional_info: 'שנת 1966 — תקופת מיתון חמורה באשדוד. הלשכה טיפלה בגל פיטורים של 1,700 פועלים. מהווה עדות לעיר של פועלים ונמל.',
    created_at: new Date('2024-01-01').toISOString(),
    updated_at: new Date('2024-01-01').toISOString(),
  },
  {
    id: '10',
    city_registry_id: 'ASH-010',
    name: 'בית מלון ראשון',
    address: 'רח׳ הראשונים 43',
    neighborhood: 'רובע א׳',
    lat: 31.8120, lng: 34.6480,
    parcel: '2085/22',
    style: 'בית מלון',
    historical_periods: ['תקופה ישראלית'],
    owner: 'פרטיים',
    documentation_reason: 'היסטורית',
    current_use: 'קיים',
    protection_level: 'ב',
    status: 'לא_התחיל',
    is_complex: false, year_built_verified: false, architect_verified: false,
    building_type: 'בית מלון',
    preservation_reasons: ['היסטורית'],
    priority_level: 'בינונית',
    full_description: 'בנוי בראשית שנות ה-60, מבנה "שכון" בן 3 קומות ששימש כבית המלון הראשון באשדוד. שימש לאחר מכן כמשרד קצין העיר הצבאי. עדות לצמיחה המהירה של העיר שהצריכה תשתית אירוח מוקדמת.',
    additional_info: 'מיאמי הוטל הוא בית המלון הוותיק ביותר הפעיל באשדוד. מבנה זה קדם לו ושימש מבקרים ופקידים בתקופת הקמת הנמל.',
    created_at: new Date('2024-01-01').toISOString(),
    updated_at: new Date('2024-01-01').toISOString(),
  },
  {
    id: '11',
    city_registry_id: 'ASH-011',
    name: 'פארק נחל לכיש',
    address: 'נחל לכיש',
    neighborhood: 'נחל לכיש',
    lat: 31.7870, lng: 34.6337,
    style: 'פארק',
    historical_periods: ['תקופה ישראלית'],
    owner: 'ממ"י / חנ"י',
    documentation_reason: 'נופית, אקולוגית',
    current_use: 'קיים - פתוח לציבור',
    protection_level: 'א',
    status: 'לא_התחיל',
    is_complex: false, year_built_verified: true, year_built: 1996, architect_verified: false,
    building_type: 'פארק',
    preservation_reasons: ['נופית', 'אקולוגית'],
    priority_level: 'גבוהה',
    full_description: 'פארק של 650 דונם הוקם בשנת 1996 לאורך הגדה הדרומית של נחל לכיש. כולל שבילי הליכה ואופניים, בעלי חיים (אנטילופות, זברות, אילות, יענים). כניסה חופשית. מהווה מסדרון אקולוגי חיוני לנחלת הלכיש.',
    additional_info: 'חלק מפרויקט שיקום נחל לכיש הארצי. מנוהל על ידי עיריית אשדוד וחברת נופי הארץ. מהווה ריאות ירוקות לתושבי העיר.',
    gov_sources: ['https://visit.ashdod.muni.il/en/night-life/lachish-park/'],
    created_at: new Date('2024-01-01').toISOString(),
    updated_at: new Date('2024-01-01').toISOString(),
  },
  {
    id: '12',
    city_registry_id: 'ASH-012',
    name: 'שדרת השקמים',
    address: 'דרום (שד׳ השקמים)',
    neighborhood: 'דרום',
    lat: 31.785, lng: 34.64,
    style: 'גנון / שדרה',
    historical_periods: ['תקופה ישראלית', 'תקופות קדומות'],
    owner: 'ממ"י / עיריית אשדוד',
    documentation_reason: 'אקולוגית, נופית',
    current_use: 'קיים',
    protection_level: 'ב',
    status: 'לא_התחיל',
    is_complex: false, year_built_verified: false, architect_verified: false,
    building_type: 'גנון / שדרה',
    preservation_reasons: ['אקולוגית', 'נופית'],
    priority_level: 'בינונית',
    full_description: 'שדרה היסטורית של עצי שקמה עתיקים (Ficus sycomorus) בדרום אשדוד. עצי שקמה הם עצים מקראיים — מוזכרים בתנ"ך כעצי השפלה. מייצגים שכבה ביולוגית היסטורית של אזור אשדוד. שמירה על מערכת אקולוגית ייחודית.',
    additional_info: 'עץ השקמה (שקמה מקראית / Ficus sycomorus) הוא עץ מסורתי ארץ-ישראלי המוזכר במקרא. מהווה בית גידול לעופות ושמירה על מגוון ביולוגי.',
    created_at: new Date('2024-01-01').toISOString(),
    updated_at: new Date('2024-01-01').toISOString(),
  },
  {
    id: '13',
    city_registry_id: 'ASH-013',
    name: 'תל מור',
    address: 'דרום אשדוד — פי הנחל',
    neighborhood: 'דרום',
    lat: 31.7654, lng: 34.6412,
    style: 'תל ארכאולוגי',
    historical_periods: ['תקופות קדומות', 'תקופת הברונזה', 'תקופת הברזל', 'תקופה פרסית-הלניסטית'],
    owner: 'קרקע ציבורית',
    documentation_reason: 'ארכאולוגית',
    current_use: 'קיים',
    protection_level: 'א',
    status: 'לא_התחיל',
    is_complex: false, year_built_verified: false, architect_verified: false,
    building_type: 'תל ארכאולוגי',
    preservation_reasons: ['ארכאולוגית'],
    priority_level: 'גבוהה',
    full_description: 'תל ארכאולוגי עתיר ממצאים בפי נחל לכיש, ליד נמל אשדוד. מקובץ יישוב מהתקופה הפלשתית, רומית ופרסית. חפירות גילו מבצר מהברונזה המאוחרת (כ-1400 לפנה"ס), בתים, מבנים ציבוריים, מערכות מים, כלי חרס, תכשיטים ונשק.',
    iaa_reference: 'A-1433/1986',
    additional_info: 'חפירה בשנת 1986 בניהול י. אלדר, רשות העתיקות. מספר אתר IAA: A-1433. תל מור שלט על כניסת הספינות לפי הנחל בתקופות קדומות.',
    gov_sources: ['https://www.biblewalks.com/telmor/'],
    created_at: new Date('2024-01-01').toISOString(),
    updated_at: new Date('2024-01-01').toISOString(),
  },
  {
    id: '14',
    city_registry_id: 'ASH-014',
    name: 'מצודת אשדוד ים',
    address: 'חוף הים — אשדוד ים',
    neighborhood: 'חוף',
    lat: 31.8076, lng: 34.6089,
    style: 'מצודה ארכאולוגית',
    historical_periods: ['תקופות קדומות', 'תקופה ביזנטית', 'תקופה אסלאמית קדומה'],
    owner: 'ממ"י',
    documentation_reason: 'ארכאולוגית, נופית',
    current_use: 'קיים - טיילת חוף',
    protection_level: 'א',
    status: 'לא_התחיל',
    is_complex: false, year_built_verified: false, architect_verified: false,
    building_type: 'מצודה ארכאולוגית',
    preservation_reasons: ['ארכאולוגית', 'נופית'],
    priority_level: 'גבוהה',
    full_description: 'מצודה חופית רב-תקופתית — מהברונזה המאוחרת ועד התקופה האסלאמית הקדומה. מבצר אסלאמי קדום (40x60 מ׳) — מזוהה עם ה"ריבאט" שנזכר אצל אל-מוקדסי (המאה ה-10). חפירות IAA בשנים 1997-1999. כולל מתחם כנסיה ביזנטית ושרידים הלניסטיים.',
    iaa_reference: 'חפירות IAA 1997-1999',
    additional_info: 'שמורה בתב"ע 122/101/02/3. הריבאט האסלאמי הוא מבנה ביצור דתי ששימש לשמירה על החוף. האתר נחפר לאחר שנחשף בסיפוח לשטח הבנייה של אשדוד.',
    gov_sources: ['https://archaeological.wixsite.com/ashdodyam/copy-of-introducing-ashdod-yam'],
    created_at: new Date('2024-01-01').toISOString(),
    updated_at: new Date('2024-01-01').toISOString(),
  },
];
