import { Route } from '@/lib/types';

export const DEMO_ROUTES: Route[] = [
  {
    id: 'route-1',
    title: 'שנות ה-60: העיר מתעצבת',
    description: 'מסלול בין המבנים הציבוריים הראשונים שהוקמו באשדוד — מלשכת העבודה דרך הקליפורניות ועד בית קנדה. סיפור של עיר צעירה שצומחת.',
    theme: 'תקופה',
    cover_image_url: null,
    created_by: 'system',
    is_public: true,
    created_at: new Date('2024-06-01').toISOString(),
    updated_at: new Date('2024-06-01').toISOString(),
    sites: [
      { id: 'rs-1', route_id: 'route-1', building_id: '9', position: 1, narrative_text: 'לשכת העבודה — המפגש הראשון של עולים חדשים עם מקום עבודה בעיר הצעירה.' },
      { id: 'rs-2', route_id: 'route-1', building_id: '10', position: 2, narrative_text: 'בית המלון הראשון שירת פקידים ומבקרים בתקופת הקמת הנמל.' },
      { id: 'rs-3', route_id: 'route-1', building_id: '4', position: 3, narrative_text: 'הקליפורניות — הבנקים הראשונים. תחילת הפעילות הכלכלית.' },
      { id: 'rs-4', route_id: 'route-1', building_id: '5', position: 4, narrative_text: 'בית קנדה — מרכז קליטה ברוטליסטי. כאן התחילו חייהם של אלפי עולים.' },
      { id: 'rs-5', route_id: 'route-1', building_id: '8', position: 5, narrative_text: 'הגן האדום — גן הילדים הראשון. כאן גדל הדור הראשון של ילדי אשדוד.' },
    ],
  },
  {
    id: 'route-2',
    title: 'מהעת העתיקה ועד היום',
    description: 'מסלול ארכאולוגי — מתל מור דרך מצודת אשדוד ים ועד גשר עד הלום. אלפי שנים של היסטוריה על קו החוף.',
    theme: 'ארכאולוגיה',
    cover_image_url: null,
    created_by: 'system',
    is_public: true,
    created_at: new Date('2024-06-01').toISOString(),
    updated_at: new Date('2024-06-01').toISOString(),
    sites: [
      { id: 'rs-6', route_id: 'route-2', building_id: '13', position: 1, narrative_text: 'תל מור — יישוב עתיק בפי הנחל. מבצר מהברונזה המאוחרת שלט על כניסת הספינות.' },
      { id: 'rs-7', route_id: 'route-2', building_id: '14', position: 2, narrative_text: 'מצודת אשדוד ים — ריבאט אסלאמי וכנסיה ביזנטית. שכבות של תרבויות על חוף הים.' },
      { id: 'rs-8', route_id: 'route-2', building_id: '2', position: 3, narrative_text: 'גשר עד הלום — מהמאה ה-13 ועד 1948. כאן נעצרה ההתקדמות המצרית.' },
      { id: 'rs-9', route_id: 'route-2', building_id: '3', position: 4, narrative_text: 'האובליסק — סמל הפיוס. מצרים וישראל מנציחות יחד את זיכרון הקרב.' },
    ],
  },
  {
    id: 'route-3',
    title: 'רובע א׳ — שכונת האם',
    description: 'סיור ברובע א׳ — השכונה הראשונה של אשדוד. מהמרכז הרובעי דרך בית הכנסת הקראי ועד הגן האדום.',
    theme: 'שכונה',
    cover_image_url: null,
    created_by: 'system',
    is_public: true,
    created_at: new Date('2024-06-01').toISOString(),
    updated_at: new Date('2024-06-01').toISOString(),
    sites: [
      { id: 'rs-10', route_id: 'route-3', building_id: '7', position: 1, narrative_text: 'המרכז הרובעי — הלב הפועם. קולונדה, עמודים, בריכת מים ציבורית. תכנון על פי עקרונות CIAM.' },
      { id: 'rs-11', route_id: 'route-3', building_id: '5', position: 2, narrative_text: 'בית קנדה — בטון חשוף, חצרות פנימיות, דירות זעירות. כאן התחילו חיים חדשים.' },
      { id: 'rs-12', route_id: 'route-3', building_id: '6', position: 3, narrative_text: 'בית הכנסת הקראי — מרכז הקהילה הקראית הגדולה בישראל. מסורת ייחודית.' },
      { id: 'rs-13', route_id: 'route-3', building_id: '8', position: 4, narrative_text: 'הגן האדום — זיכרון ילדות. גן הילדים הראשון של העיר.' },
    ],
  },
  {
    id: 'route-4',
    title: 'טבע ונוף — המסדרון הירוק',
    description: 'מסלול טבע — מפארק נחל לכיש דרך שדרת השקמים ועד המגדלור בגבעת יונה. טבע, אקולוגיה ונוף.',
    theme: 'טבע',
    cover_image_url: null,
    created_by: 'system',
    is_public: true,
    created_at: new Date('2024-06-01').toISOString(),
    updated_at: new Date('2024-06-01').toISOString(),
    sites: [
      { id: 'rs-14', route_id: 'route-4', building_id: '11', position: 1, narrative_text: 'פארק נחל לכיש — 650 דונם, בעלי חיים, שבילי הליכה. מסדרון אקולוגי חיוני.' },
      { id: 'rs-15', route_id: 'route-4', building_id: '12', position: 2, narrative_text: 'שדרת השקמים — עצים מקראיים. שכבה ביולוגית היסטורית של אזור אשדוד.' },
      { id: 'rs-16', route_id: 'route-4', building_id: '1', position: 3, narrative_text: 'המגדלור בגבעת יונה — 138 מטר. הנקודה הגבוהה ביותר באשדוד. שלושה הבזקים כל 20 שניות.' },
    ],
  },
];
